# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      STAGE: qa

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy SST to QA
      run: npx sst deploy --stage qa
    
    - name: Extract ARN and set as output
      id: get-arn
      run: |
        ARN=$(jq -r '.stack.computeRole.arn' .sst/outputs.json)
        echo "compute_role_arn=$ARN" >> $GITHUB_OUTPUT

    - name: Set compute role ARN as environment variable
      run: echo "COMPUTE_ROLE_ARN=${{ steps.get-arn.outputs.compute_role_arn }}" >> $GITHUB_ENV

    - name: Update Amplify App with compute role
      run: |
          aws amplify update-app \
            --app-id d1elq7oppdpwa6 \
            --branch-name master \
            --compute-role-arn ${{ steps.get-arn.outputs.compute_role_arn }}
